In [4]:
import pandas as pd
from statsmodels.tsa.arima.model import ARIMA
import matplotlib.pyplot as plt
data = pd.read_csv('sum.csv')
data.head()

,Năm,Tháng,Chỉ tiêu,Ước tính mỗi tháng,Tổng lượt khách cả năm,So với tháng trước (%),So sánh tháng này ở năm trước(%),So sánh tổng lượt khách với cùng kỳ năm trước (%),Unnamed: 8,Unnamed: 9
0,2019,t1,Tổng số,1.374.235,1.501.766,"109,3","105,0",NaN,NaN,NaN
1,2019,t2,Tổng số,1.588.161,3.089.927,"105,8","110,9","108,0",NaN,NaN
2,2019,t3,Tổng số,1.410.187,4.500.114,"88,8","105,0","107,0",NaN,NaN
3,2019,t4,Tổng số,1.468.766,5.968.880,"104,2","109,5","107,6",NaN,NaN
4,2019,t5,Tổng số,1.326.668,7.295.548,"90,3","114,3","108,8",NaN,NaN

In [3]:
# Chỉ sử dụng cột "Ước tính mỗi tháng" cho dự đoán
series = filtered_data['Ước tính mỗi tháng']

# Tạo chỉ số thời gian
filtered_data['time'] = filtered_data['Năm'].astype(str) + '-' + filtered_data['Tháng'].str.extract('(\d+)')[0]
filtered_data['time'] = pd.to_datetime(filtered_data['time'], format='%Y-%m')
filtered_data.set_index('time', inplace=True)
filtered_data.sort_index(inplace=True)

# Chia dữ liệu train và test (tách năm 2024)
train = series[:'2023']
test = series['2024']

# Xây dựng mô hình ARIMA
model = ARIMA(train, order=(1, 1, 1))
model_fit = model.fit()

# Dự đoán cho năm 2024
forecast = model_fit.forecast(steps=len(test))

# Vẽ biểu đồ so sánh thực tế và dự đoán
plt.figure(figsize=(10, 6))
plt.plot(series, label='Thực tế')
plt.plot(forecast, label='Dự đoán', linestyle='--', color='orange')
plt.title('Dự đoán lượng khách - ARIMA (Ước tính mỗi tháng)')
plt.legend()
plt.show()

forecast, test

<class 'pandas.core.frame.DataFrame'>
Index: 36 entries, 1 to 70
Data columns (total 8 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Năm                                                36 non-null     int64
 1   Tháng                                              36 non-null     object
 2   Chỉ tiêu                                           36 non-null     object
 3   Ước tính mỗi tháng                                 36 non-null     float64
 4   Tổng lượt khách cả năm                             36 non-null     float64
 5   So với tháng trước (%)                             36 non-null     float64
 6   So sánh tháng này ở năm trước(%)                   36 non-null     float64
 7   So sánh tổng lượt khách với cùng kỳ năm trước (%)  36 non-null     float64
dtypes: float64(5), int64(1), object(2)
memory usage: 2.5+ KB

(None,
     Năm Tháng Chỉ tiêu  Ước tính mỗi tháng  Tổng lượt khách cả năm  \
 1  2019    t2  Tổng số           1588161.0               3089927.0
 2  2019    t3  Tổng số           1410187.0               4500114.0
 3  2019    t4  Tổng số           1468766.0               5968880.0
 4  2019    t5  Tổng số           1326668.0               7295548.0
 5  2019    t6  Tổng số           1185445.0               8480993.0

    So với tháng trước (%)  So sánh tháng này ở năm trước(%)  \
 1                   105.8                             110.9
 2                    88.8                             105.0
 3                   104.2                             109.5
 4                    90.3                             114.3
 5                    89.4                             100.2

    So sánh tổng lượt khách với cùng kỳ năm trước (%)
 1                                              108.0
 2                                              107.0
 3                                              107.6
 4                                              108.8
 5                                              107.5  )